language: node_js
node_js:
- '0.12'
before_script:
- npm install -g component
- npm install -g harp
- cd site
- component install
- component build
- cd ..
- chmod +x ./deploy.sh
script:
- mkdir /tmp/__temp_static_content
- harp compile ./site /tmp/__temp_static_content
- cp .gitignore /tmp/__temp_static_content
- ls /tmp/__temp_static_content
after_success: "./deploy.sh"
env:
  global:
    secure: a22vObw4/UzWBQvc1YTlb0sbB7cfpr2lj99RQKnSdanZ0H4CSwMei0G0vXZYfWu3MNi5TIr/g8ox0hHawlIFJfEv0aP8nFxbQdeJ4SEgBD5FC7RiDwH7/AZzyQnZxg+yj5DDAi+q5eP9h6EdQsovkXUm9uEX/BiXkXlQpV7XPdU=
